Task_1_1_1
h1km4t1ll0/OOP pull request #3
Opened 2023-09-26 05:23 UTC by h1km4t1ll0

2023-09-26 17:09 UTC, h1km4t1ll0 commented
Я дико извиняюсь за просроченный на 8 минут дедлайн, в последний момент понял, что не сделал тесты для main метода. До этого был отдельный Main класс для этого

2023-10-03 03:27 UTC, shadrina reviewed
Переделай пожалуйста и я засчитаю

2023-10-03 03:27 UTC, shadrina commented on Task_1_1_1/src/main/java/ru/nsu/dolgov/HeapSort.java
> +    }
В этом классе состояние избыточно: вы получаете входной массив, меняете его и возвращаете (или просто меняете). Все методы могли бы быть статическими, поле и конструктор можно убрать.

2023-10-03 03:27 UTC, shadrina commented on Task_1_1_1/src/test/java/ru/nsu/dolgov/HeapSortTest.java
> +        final HeapSort sampleInstance = new HeapSort(
И тогда вот здесь тоже не понадобятся инстансы

2023-10-03 03:28 UTC, shadrina commented
Еще надо в основной ветке удалить лишний подмодуль отдельным PR или напрямую

2023-10-09 07:39 UTC, h1km4t1ll0 commented
> Еще надо в основной ветке удалить лишний подмодуль отдельным PR или напрямую

у меня локально его нет, по идее, если вмержить эту ветку, то пропадет подмодуль

2023-10-09 08:29 UTC, shadrina requested changes

2023-10-09 08:29 UTC, shadrina commented on Task_1_1_1/build.gradle
> +group = 'ru.nsu.shadrina'
Группа не та

2023-10-09 08:29 UTC, shadrina commented on Task_1_1_1
Убери пожалуйста вот это изменение из PR. Для этого надо модуль удалить отдельно в ветке main

2023-10-10 01:43 UTC, h1km4t1ll0 commented on Task_1_1_1/build.gradle
> +group = 'ru.nsu.shadrina'
группу поменял, добавил package heapsort

2023-10-16 09:49 UTC, shadrina commented
> > Еще надо в основной ветке удалить лишний подмодуль отдельным PR или напрямую
> 
> у меня локально его нет, по идее, если вмержить эту ветку, то пропадет подмодуль

У тебя он есть локально в ветке `main`. Из этой ветки его надо удалить и залить отдельно. Тогда в этом PR это измнение само исчезнет.

2023-10-16 10:43 UTC, shadrina requested changes
Если не получается справиться с подмодулем, подходи на паре

2023-11-04 11:10 UTC, shadrina approved these changes
Ура

2023-11-04 11:32 UTC, merged