Task_1_1_2
h1km4t1ll0/OOP pull request #4
Opened 2023-09-26 17:13 UTC by h1km4t1ll0

2023-10-10 04:10 UTC, shadrina requested changes
Задача не собирается, обрати внимание на вкладку Files changed и структуру изменений

2023-11-04 11:32 UTC, merged

2023-11-04 13:19 UTC, shadrina commented
Почему задача merged? Она не собиралась и нет approve.

2023-11-04 18:54 UTC, h1km4t1ll0 commented
Ой ой ой, яне то сиержииил

2023-11-04 19:02 UTC, h1km4t1ll0 commented
Хотя секунду, эту ветку я не трогал, я мержил только 1_1_1
<img width="1243" alt="image" src="https://github.com/h1km4t1ll0/OOP/assets/67962904/e0e07b3e-1c2a-4dee-82b8-16066693e212">

2023-11-04 19:08 UTC, h1km4t1ll0 commented
коммиты совпадают, поэтому гитхаб посчитал, что этот ПР тоже можно закрыть, я пересоздам ветку сделаю новый ПР, в репу все равно ничего не попало