Task_1_2_1
h1km4t1ll0/OOP pull request #5
Opened 2023-10-17 03:32 UTC by h1km4t1ll0

2023-10-28 10:12 UTC, shadrina requested changes
А подмодуль и ныне там)

2023-10-28 10:12 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/dolgov/tree/Tree.java
> +        return this.value.equals(otherTree.value);
На паре прошлой вас попросила еще раз всех проверить свою реализацию equals, в том числе на то, что она не просто проверяет одну верхнюю ноду, а проверяет все поддерево.

2023-10-28 10:12 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/dolgov/tree/Tree.java
> +        return this.value.equals(otherTree.value);
Оно проверяет ровно родителя и равенство значений в верхей ноде

2023-10-28 11:19 UTC, h1km4t1ll0 commented on Task_1_2_1/src/main/java/ru/nsu/dolgov/tree/Tree.java
> +        return this.value.equals(otherTree.value);
подождите, но ведь я показывал вам этот код на семинаре. В точности этот код и вы сказали, что все хорошо. Я поправил реализацию equals, убрав оттуда хешкоды, как вы сказали на паре и все. Про эту странную реализацию вы сказали "пусть будет"

2023-10-28 11:21 UTC, h1km4t1ll0 commented
по поводу подмодуля. Вот files changed. разве он не удалится при мерже?
<img width="1148" alt="image" src="https://github.com/h1km4t1ll0/OOP/assets/67962904/e4298206-d091-4a3c-ad57-869692017054">

2023-10-28 11:26 UTC, shadrina commented
Нет, Files changed это изменения данного PR, то есть сравнение состояния текущей ветки и ветки `main`. А в `main` модуль остался, оттуда отдельным PR или прямым коммитом его никто не убирал.

2023-10-28 11:29 UTC, h1km4t1ll0 commented
можно я подойду на семинаре с этим вопросом? в папке .git этого подмодуля нет, папки .submodules тоже нет

2023-10-28 11:31 UTC, shadrina commented
Подходи

2023-10-28 11:31 UTC, h1km4t1ll0 commented
по поводу equals. Нужно все таки написать рекурсивный обход дерева, чтобы ПР был закрыт?

2023-10-28 11:32 UTC, h1km4t1ll0 commented
ну и убрать сравнение родителей у деревьев)

2023-10-29 04:45 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/dolgov/tree/Tree.java
> +        return this.value.equals(otherTree.value);
Я сказала "пусть будет" на сравнение родителей. Про то, что надо сравнивать все поддерево, а не только верхнюю ноду, сказала в самом начале паре всем сразу. Ну у тебя два совсем разных дерева с одинаковой верхушкой будут равны, разве это то, что хочется?

2023-10-29 04:46 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/dolgov/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
Почему тут assertNotSame, а не assertNotEquals? Понимаешь разницу между `==` и `.equals()`?

2023-10-29 04:47 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/dolgov/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
Аналогично. Почему-то при проверке на равенство равных используешь assertEquals, а при проверке на неравенство assertNotSame. Как так?)

2023-10-29 05:28 UTC, h1km4t1ll0 commented on Task_1_2_1/src/test/java/ru/nsu/dolgov/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
Все понял, переделаю, сегодня обновлю ПР. Извините, что недопонял)

2024-02-26 12:29 UTC, closed without merging