Task_1_4_1
h1km4t1ll0/OOP pull request #7
Opened 2023-11-28 04:23 UTC by h1km4t1ll0

2023-11-28 08:52 UTC, shadrina requested changes
Варнинги от ревьюдога

2023-11-28 08:52 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/CreditBook.java
> +    Map<Integer, List<Subject>> semesters;
Сделай пожалуйста отдельный класс с человеко-читаемым названием и соответствующим API, который внутри будет содержать вот эту мапу списков. Типа `Semesters`

2023-11-28 08:52 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/CreditBook.java
> +        }
Stream API please

2023-11-28 08:52 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/CreditBook.java
> +        return true;
Stream API please

2023-11-28 08:52 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/CreditBook.java
> +        }
Stream API please

2023-11-28 15:03 UTC, h1km4t1ll0 commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/CreditBook.java
> +        }
Stream API сделал, класс Semesters добавил, ворнинги ревью-собаки убрал

2023-12-05 04:16 UTC, shadrina approved these changes

2023-12-05 04:16 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/Semesters.java
> +    Map<Integer, List<Subject>> semestersMap;
Под длинные параметризованные типы лучше создавать отдельный класс с человекочитаемым названием и понятным простым API

2023-12-05 04:18 UTC, h1km4t1ll0 commented on Task_1_4_1/src/main/java/ru/nsu/dolgov/creditbook/Semesters.java
> +    Map<Integer, List<Subject>> semestersMap;
так я же и сделал отдельный класс под семестры, вынес его отдельно

2023-12-05 05:17 UTC, merged