Task_1_5_1
h1km4t1ll0/OOP pull request #8
Opened 2023-12-05 16:59 UTC by h1km4t1ll0

2023-12-08 13:02 UTC, h1km4t1ll0 commented
@shadrina добрый вечер! Я могу попросить вас посмотреть ПР, я сделал его в рамках мягкого дедлайна

2023-12-12 09:27 UTC, shadrina requested changes

2023-12-12 09:27 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Expression.java
> +    public String[] rawTokens;
Инкапсуляция?

2023-12-12 09:27 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            case "sin": {
Сделай хотя бы enum для операций.

2023-12-12 09:27 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Expression.java
> +public class Expression {
Мне не очень понятна эта абстракция. Зачем она нужна? В данном случае она просто держит два филда, доступ к которым осуществляется напрямую. Никакой дополнительной логики не задает, ничего не упрощает. Надо пересмотреть архитектуру. У абстракции должна быть четко опеределена ответственность.

2023-12-12 09:27 UTC, shadrina commented on Task_1_5_1/src/test/java/ru/nsu/dolgov/calculator/CalculatorTest.java
> +    void testLogInvalidNumberException() {
- Нет тестов с нецелочисленными значениями
- Нет большого теста, в котором использовались бы все операции

2023-12-12 10:05 UTC, h1km4t1ll0 commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            case "sin": {
@shadrina не совсем понимаю смысла в енуме, все равно будет огромная борода из свитч-кейсов, т.к. мы парсим операцию из строки

2023-12-12 10:06 UTC, h1km4t1ll0 commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            case "sin": {
Может, без него обойтись?

2023-12-12 11:13 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            case "sin": {
Enum нужен, чтобы не забыть никакую из констант при очередном написании свича по каждому значению. В случае со строкой, компилятор спокойно проглотит, в случае с enum'ом - не даст скомпилировать.

2023-12-12 11:54 UTC, h1km4t1ll0 commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            case "sin": {
Хм, логично. Спасибо огромное за ответ, все переделаю

2023-12-12 16:22 UTC, h1km4t1ll0 commented
добавил енум, добавил е2е тест, тесты с дробными аргументами, добавил функциональность к классу Expression. Expression, в моем понимании, класс, который должен хранить в себе распарсенное выражение для того, чтобы калькулятор мог использовать апи Expression для того, чтобы этот Expression считать. Также теперь там лежит два утилитарных метода isOperand и isNumber

2023-12-18 10:09 UTC, shadrina approved these changes

2023-12-18 10:09 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            }
А если ни то, ни другое?

2023-12-18 10:09 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/dolgov/calculator/Calculator.java
> +            }
Вижу, что ниже валидация

2023-12-18 10:37 UTC, merged